model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
prompt_train: "prompts_train.csv"
prompt_val: "prompts_val.csv"
prompt_test: "prompts_test.csv"
max_new_tokens: 10
beam_width: 1
top_k: 50
top_p: 0.9
include_token_count: true
lr: 0.0001
early_stopping: 10
val_freq: 1000
epochs: 10
save_path: "checkpoints/regression_model.pt"
scheduler_type: "cosine_warm_restarts" 
T_max: 10
eta_min: 0.000001
T_0: 2
T_mult: 2
train_outputs_file: "outputs/train_generations.jsonl"
val_outputs_file: "outputs/val_generations.jsonl"
wandb_project: "cs224-project"
wandb_entity: "cs224-sjob"